version: "3"
services: 
    nifi_docker:
        image: apache/nifi:latest
        restart: always
        container_name: nifi
        ports:
            - 8181:8181
        environment:
            - NIFI_WEB_HTTP_PORT=8181
        volumes:
            - ./nifi/content:/opt/nifi/nifi-current/content_repository
            - ./nifi/db:/opt/nifi/nifi-current/database_repository
            - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
            - ./nifi/state:/opt/nifi/nifi-current/state
            #- ./nifi/logs:/opt/nifi/nifi-current/logs
            - ./nifi/data:/opt//nifi/nifi-current/data
            - ./nifi/templates:/opt/nifi/conf/templates/